config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :meals do
    resources :reviews, only: %i(index new create)
  end
  resources :reviews, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :reviews, dependent: :destroy
  belongs_to :user
  validates :title, :description, :rating, :user, :capacity, presence: true
  has_one_attached :photo
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :meal
  validates :title, :content, :rating, :meal, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :meals, dependent: :destroy
  has_many :reviews, dependent: :destroy
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = 'You are not authorized to perform this action.'
  #   redirect_to(meals_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]
  def index
    @meals = policy_scope(Meal)
  end

  def new
    @meal = Meal.new
    authorize @meal
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.user = current_user
    authorize @meal
    if @meal.save
      redirect_to meals_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    @meal.user = current_user
    if @meal.update(meal_params)
      redirect_to meals_path
    else
      render 'edit'
    end
  end

  def destroy
    @meal.destroy
    redirect_to meals_path
  end

  private

  def meal_params
    params.require(:meal).permit(:title, :description, :rating, :capacity, :photo)
  end

  def set_meal
    @meal = Meal.find(params[:id])
    authorize @meal
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_meal, only: %i[new create]
  before_action :set_review, only: %i[destroy]

  def index
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.meal = @meal
    if @review.save
      redirect_to meal_path(@meal)
    else
      render 'new'
    end
  end

  def destroy
    if @review.destroy
      redirect_to meal_path(@review.meal)
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :content, :rating)
  end

  def set_meal
    @meal = Meal.find(params[:meal_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommunityTrash</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/meals/_form.html.erb
<%= simple_form_for @meal do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :rating %>
  <%= f.input :capacity %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/meals/edit.html.erb
<div class="container">
  <div class="row">
    <h3>New Meal</h3>
    <div class="col-4 offset-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/meals/index.html.erb
<div class="container">
  <h3>Meals</h3>
  <div class="row justify-content-center">
    <% @meals.each do |meal| %>
      <div class="col-md-3">
        <div class="card" >
          <div class="card-body text-white" style="<% if meal.photo.attached? %>background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path meal.photo.key, crop: :fit %>');<% end %> transform: rotate(0);">
            <div class="text-center">
              <h3><%= meal.title %></h3>
              <p><%= meal.description %></p>
            </div>
            <div class="d-flex justify-content-between">
              <p>Cap.: <%= meal.rating %></p>
              <p>Rating: <%= meal.capacity %></p>
            </div>
            <a href="<%= meal_path(meal) %>" class="stretched-link"></a>
          </div>
          <% if policy(meal).edit? && policy(meal).destroy? %>
            <div class="card-footer d-flex justify-content-between align-items-center">
              <div>
                <%= link_to "edit", edit_meal_path(meal) %>
              </div>
              <div>
                <%= link_to "destroy", meal_path(meal), method: :delete, data:{confirm: "Are you Sure?"} %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row mt-3">
    <div class="col-8 offset-2">
      <%= link_to "create a new meal", new_meal_path, class: "btn btn-primary btn-block" %>
    </div>
  </div>
</div>

app/views/meals/show.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-8 offset-2">
      <div class="card">
        <div class="card-body">
          <div class="text-center">
            <h3><%= @meal.title %></h3>
            <p><%= @meal.description %></p>
          </div>
          <div class="d-flex justify-content-between">
            <p>Capacity: <%=@meal.rating %></p>
            <p>Rating: <%= @meal.capacity %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <hr>
      <div class="d-flex justify-content-end">
        <%= link_to "New Review", new_meal_review_path(@meal), class: "badge badge-secondary" %>
      </div>
      <div>
        <h3 class="text-center">Reviews</h3>
      </div>
    </div>
  </div>
</div>
<div class="row m-1">
  <% @meal.reviews.each do |review| %>
    <div class="col-sm-4">
      <div class="card position-relative">
        <div class="card-body pb-0">
          <h5 class="text-center"><%= review.title %></h5>
          <hr class="">
          <div class="d-flex justify-content-center mb-3">
            <% review.rating.times do %>
              <i class="fas fa-star mx-1 text-warning"></i>
            <% end %>
            <% (5 - review.rating).times do %>
              <i class="far fa-star mx-1"></i>
            <% end %>
          </div>
        </div>
        <%= link_to review_path(review), method: :delete, class: "close_cross" do %>
          <i class="fas fa-times-circle"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="row mt-5">
  <div class="col-6 offset-3">
    <%= link_to "back", meals_path, class: "btn btn-primary btn-block" %>
  </div>
</div>
</div>

app/views/pages/home.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<%= link_to "meals", meals_path%>

app/views/reviews/_form.html.erb
<%= simple_form_for [@meal, @review] do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.button :submit %>
<% end %>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <h3>New Meal</h3>
    <div class="col-4 offset-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
  <div>
    <%= link_to "CommunEATy", root_path, class: "navbar-brand" %>
  </div>
  <div class="d-flex">
    <% if user_signed_in? %>
      <div class="mx-1">
        <button type="text" class="btn btn-secondary btn-outline" disabled=""><%= current_user.email%>
          <% if current_user.admin %>
            <span class="badge badge-success">A</span>
          <% end %>
        </button>
      </div>
      <%= link_to "Logout", destroy_user_session_path, method: :delete , class: "btn btn-secondary btn-outline" %>
    <% else %>
      <%= link_to "Login", new_user_session_path , class: "btn btn-success" %>
    <% end %>
  </div>
</nav>